function ChatBox.AddSound( trigger, ... )
	local args = { ... }
	if not ( trigger ) then return end
	if not ( args ) then return end
	
	for k, v in pairs( args ) do
		if ( type( args[k] ) == "boolean" ) then args[k] = nil end
	end

	table.insert( ChatBox.Sounds, { ["trigger"] = trigger, ["sound"] = args } )
end

ChatBox.AddSound("enough of your mumbo jumbo", "vo/npc/male01/vanswer01.wav", true)
ChatBox.AddSound("bullshit", "vo/npc/male01/question26.wav")
ChatBox.AddSound("yay", "vo/npc/Barney/ba_yell.wav")
ChatBox.AddSound("shit", "vo/npc/Barney/ba_ohshit03.wav")
ChatBox.AddSound("hax", "vo/npc/male01/hacks01.wav", true)
ChatBox.AddSound("hacks", "vo/npc/male01/hacks02.wav", true)
ChatBox.AddSound("h4x", "vo/npc/male01/thehacks01.wav", true)
ChatBox.AddSound("h4cks", "vo/npc/male01/thehacks02.wav", true)
ChatBox.AddSound("okay", "vo/npc/male01/ok01.wav", "vo/npc/male01/ok02.wav")
ChatBox.AddSound("derka", "vo/npc/vortigaunt/vortigese12.wav", "vo/npc/vortigaunt/vortigese11.wav", true)
ChatBox.AddSound("noes", "vo/npc/Alyx/ohno_startle01.wav", true)
ChatBox.AddSound("get down", "vo/npc/Barney/ba_getdown.wav", "vo/npc/male01/getdown02.wav")
ChatBox.AddSound("gtfo", "vo/npc/male01/gethellout.wav")
ChatBox.AddSound("gtho", "vo/npc/male01/gethellout.wav")
ChatBox.AddSound("yeah", "vo/npc/male01/yeah02.wav")
ChatBox.AddSound("rofl", "vo/Citadel/br_laugh01.wav")
ChatBox.AddSound("lmao", "vo/Citadel/br_laugh01.wav")
ChatBox.AddSound("run", "vo/npc/male01/strider_run.wav")
ChatBox.AddSound("run for your life", "vo/npc/male01/runforyourlife01.wav", "vo/npc/male01/runforyourlife02.wav", "vo/npc/male01/runforyourlife03.wav")
ChatBox.AddSound("fantastic", "vo/npc/male01/fantastic01.wav", "vo/npc/male01/fantastic02.wav")
ChatBox.AddSound("headcrabs", "vo/npc/male01/headcrabs01.wav", "vo/npc/male01/headcrabs02.wav")
ChatBox.AddSound("headhumpers", "vo/npc/Barney/ba_headhumpers.wav", true)
ChatBox.AddSound("hello", "vo/coast/odessa/nlo_cub_hello.wav")
ChatBox.AddSound("eek", "ambient/voices/f_scream1.wav", true)
ChatBox.AddSound("uh oh", "vo/npc/male01/uhoh.wav")
ChatBox.AddSound("sodomy!", "vo/ravenholm/madlaugh01.wav", "vo/ravenholm/madlaugh02.wav", "vo/ravenholm/madlaugh03.wav", "vo/ravenholm/madlaugh04.wav", true)
ChatBox.AddSound("oops", "vo/npc/male01/whoops01.wav", true)
ChatBox.AddSound("shut up", "vo/npc/male01/answer17.wav")
ChatBox.AddSound("shutup", "vo/npc/male01/answer17.wav")
ChatBox.AddSound("right on", "vo/npc/male01/answer32.wav", true)
ChatBox.AddSound("freeman", "vo/npc/male01/gordead_ques03a.wav", true)
ChatBox.AddSound("help", "vo/npc/male01/help01.wav")
ChatBox.AddSound("haxz", "vo/npc/male01/herecomehacks01.wav", true)
ChatBox.AddSound("hi", "vo/npc/male01/hi01.wav", "vo/npc/male01/hi02.wav")
ChatBox.AddSound("let's go", "vo/npc/male01/letsgo01.wav", "vo/npc/male01/letsgo02.wav")
ChatBox.AddSound("lets go", "vo/npc/male01/letsgo01.wav", "vo/npc/male01/letsgo02.wav")
ChatBox.AddSound("moan", "vo/npc/male01/moan01.wav", "vo/npc/male01/moan02.wav", "vo/npc/male01/moan03.wav", "vo/npc/male01/moan04.wav", "vo/npc/male01/moan05.wav", true)
ChatBox.AddSound("nice", "vo/npc/male01/nice.wav")
ChatBox.AddSound("noo", "vo/npc/Barney/ba_no01.wav", "vo/npc/Barney/ba_no02.wav", true)
ChatBox.AddSound("nooo", "vo/npc/male01/no02.wav", true)
ChatBox.AddSound("oh no", "vo/npc/male01/ohno.wav")
ChatBox.AddSound("joygasm", "vo/npc/female01/pain06.wav", true)
ChatBox.AddSound("zombies", "vo/npc/male01/zombies01.wav", "vo/npc/male01/zombies02.wav")
ChatBox.AddSound("da man", "bot/whos_the_man.wav", true)
ChatBox.AddSound("my house", "bot/this_is_my_house.wav", true)
ChatBox.AddSound("party", "bot/its_a_party.wav", true)
ChatBox.AddSound("watch out", "vo/npc/male01/watchout.wav")
ChatBox.AddSound("excuse me", "vo/npc/male01/excuseme01.wav", "vo/npc/male01/excuseme02.wav")
ChatBox.AddSound("you sure?", "vo/npc/male01/answer37.wav")
ChatBox.AddSound("groan", "vo/npc/male01/moan04.wav", true)
ChatBox.AddSound("gasp", "vo/npc/male01/startle01.wav", "vo/npc/male01/startle02.wav", true)
ChatBox.AddSound("sorry", "vo/npc/male01/sorry01.wav", "vo/npc/male01/sorry02.wav", "vo/npc/male01/sorry03.wav")
ChatBox.AddSound("welcome to city 17", "vo/Breencast/br_welcome01.wav", "vo/Breencast/br_welcome06.wav", true)
ChatBox.AddSound("it's safer here", "vo/Breencast/br_welcome07.wav", true)
ChatBox.AddSound("i'm talking to you", "vo/Breencast/br_tofreeman02.wav", true)
ChatBox.AddSound("serve mankind", "vo/Breencast/br_tofreeman12.wav", true)
ChatBox.AddSound("get going", "vo/canals/shanty_go_nag03.wav")
ChatBox.AddSound("go on out", "vo/canals/gunboat_goonout.wav", true)
ChatBox.AddSound("get outta here", "vo/canals/shanty_go_nag01.wav", "vo/canals/boxcar_go_nag03.wav")
ChatBox.AddSound("go on", "vo/canals/shanty_go_nag02.wav")
ChatBox.AddSound("hey", "vo/canals/shanty_hey.wav")
ChatBox.AddSound("get in here hurry", "vo/canals/matt_getin.wav", true)
ChatBox.AddSound("hit the road jack", "vo/canals/boxcar_go_nag04.wav", true)
ChatBox.AddSound("no", "vo/Citadel/eli_notobreen.wav")
ChatBox.AddSound("no!", "vo/Citadel/br_failing11.wav", true)
ChatBox.AddSound("never", "vo/Citadel/eli_nonever.wav")
ChatBox.AddSound("you fool", "vo/Citadel/br_youfool.wav", true)
ChatBox.AddSound("good god", "vo/Citadel/eli_goodgod.wav")
ChatBox.AddSound("cheer", "vo/coast/odessa/male01/nlo_cheer01.wav", "vo/coast/odessa/male01/nlo_cheer02.wav", "vo/coast/odessa/male01/nlo_cheer03.wav", "vo/coast/odessa/male01/nlo_cheer04.wav", true)
ChatBox.AddSound("drive safely", "vo/coast/odessa/male01/nlo_citizen_drivesafe.wav", true)
ChatBox.AddSound("whoops", "vo/k_lab/ba_whoops.wav", true)
ChatBox.AddSound("gee thanks", "vo/k_lab/ba_geethanks.wav")
ChatBox.AddSound("what the hell", "vo/k_lab/ba_whatthehell.wav")
ChatBox.AddSound("it's your pet the freakin headhumper", "vo/k_lab/ba_headhumper01.wav", true)
ChatBox.AddSound("i'll stay here", "vo/npc/male01/illstayhere01.wav", "vo/npc/male01/imstickinghere01.wav")
ChatBox.AddSound("up there", "vo/npc/male01/upthere01.wav", "vo/npc/male01/upthere02.wav")
ChatBox.AddSound("he's dead", "vo/npc/male01/gordead_ques01.wav", "vo/npc/male01/gordead_ques07.wav", true)
ChatBox.AddSound("lead the way", "vo/npc/male01/leadtheway02.wav", "vo/npc/male01/leadtheway01.wav", true)
ChatBox.AddSound("we're done for", "vo/npc/male01/gordead_ans14.wav", true)
ChatBox.AddSound("over there", "vo/npc/male01/overthere01.wav", "vo/npc/male01/overthere02.wav")
ChatBox.AddSound("ok i'm ready", "vo/npc/male01/okimready01.wav", "vo/npc/male01/okimready02.wav", "vo/npc/male01/okimready03.wav")
ChatBox.AddSound("i'm with you", "vo/npc/male01/answer13.wav", true)
ChatBox.AddSound("hey over here", "vo/npc/male01/overhere01.wav", true)
ChatBox.AddSound("behind you", "vo/npc/male01/behindyou01.wav", "vo/npc/male01/behindyou02.wav")
ChatBox.AddSound("follow me", "vo/npc/male01/squad_away03.wav")
ChatBox.AddSound("pardon me", "vo/npc/male01/pardonme01.wav", "vo/npc/male01/pardonme02.wav")
ChatBox.AddSound("got one", "vo/npc/male01/gotone01.wav", "vo/npc/male01/gotone02.wav")
ChatBox.AddSound("finally", "vo/npc/male01/finally.wav")
ChatBox.AddSound("wait for me", "vo/npc/male01/squad_reinforce_single04.wav")
ChatBox.AddSound("i'm hurt", "vo/npc/male01/imhurt01.wav", true)
ChatBox.AddSound("take cover", "vo/npc/male01/takecover02.wav")
ChatBox.AddSound("it's a manhack", "vo/npc/male01/itsamanhack02.wav", true)
ChatBox.AddSound("incoming", "vo/npc/male01/incoming02.wav")
ChatBox.AddSound("ready when you are", "vo/npc/male01/readywhenyouare01.wav", "vo/npc/male01/readywhenyouare02.wav", true)
ChatBox.AddSound("don't forget hawaii", "vo/npc/male01/answer34.wav", true)
ChatBox.AddSound("that's enough outta you", "vo/npc/male01/answer39.wav", true)
ChatBox.AddSound("wait for us", "vo/npc/male01/squad_reinforce_group04.wav")
ChatBox.AddSound("now what?", "vo/npc/male01/gordead_ans01.wav")
ChatBox.AddSound("we trusted you", "vo/npc/male01/wetrustedyou01.wav", "vo/npc/male01/wetrustedyou02.wav", true)
ChatBox.AddSound("god i'm hungry", "vo/npc/male01/question28.wav", true)
ChatBox.AddSound("i'm ganna be sick", "vo/npc/male01/gordead_ans19.wav", true)
ChatBox.AddSound("you're talking to yourself again", "vo/npc/male01/answer09.wav", true)
ChatBox.AddSound("come on everybody", "vo/npc/male01/squad_follow02.wav", true)
ChatBox.AddSound("watch what you're doing", "vo/npc/male01/watchwhat.wav", true)
ChatBox.AddSound("your mind is in the gutter", "vo/npc/male01/answer20.wav", true)
ChatBox.AddSound("here they come!", "vo/npc/male01/heretheycome01.wav", true)
ChatBox.AddSound("same here", "vo/npc/male01/answer07.wav")
ChatBox.AddSound("i wouldn't say that too loud", "vo/npc/male01/answer10.wav", true)
ChatBox.AddSound("i'll put it on your tombstone", "vo/npc/male01/answer11.wav", true)
ChatBox.AddSound("have you ever had an original thought?", "vo/npc/male01/answer16.wav", true)
ChatBox.AddSound("let's concentrate on the task at hand", "vo/npc/male01/answer18.wav", true)
ChatBox.AddSound("keep your mind on your work", "vo/npc/male01/answer19.wav", true)
ChatBox.AddSound("you never know", "vo/npc/male01/answer22.wav", true)
ChatBox.AddSound("you never can tell", "vo/npc/male01/answer23.wav", true)
ChatBox.AddSound("why are you telling me?", "vo/npc/male01/answer24.wav", true)
ChatBox.AddSound("how about that", "vo/npc/male01/answer25.wav", true)
ChatBox.AddSound("want a bet?", "vo/npc/male01/answer27.wav")
ChatBox.AddSound("what am i supposed to do about it?", "vo/npc/male01/answer29.wav")
ChatBox.AddSound("you talking to me?", "vo/npc/male01/answer30.wav")
ChatBox.AddSound("leave it alone", "vo/npc/male01/answer38.wav", true)
ChatBox.AddSound("can't you see i'm busy?", "vo/npc/male01/busy02.wav", true)
ChatBox.AddSound("look out below", "vo/npc/male01/cit_dropper04.wav", true)
ChatBox.AddSound("shouldn't we be doing something?", "vo/npc/male01/doingsomething.wav", true)
ChatBox.AddSound("let's even the odds a little", "vo/npc/male01/evenodds.wav", true)
ChatBox.AddSound("oh god", "vo/npc/male01/gordead_ans04.wav")
ChatBox.AddSound("should we bury him here?", "vo/npc/male01/gordead_ans08.wav", true)
ChatBox.AddSound("what's the use?", "vo/npc/male01/gordead_ans11.wav", true)
ChatBox.AddSound("what's the point?", "vo/npc/male01/gordead_ans12.wav", true)
ChatBox.AddSound("this is bad", "vo/npc/male01/gordead_ques10.wav", true)
ChatBox.AddSound("hold down this spot", "vo/npc/male01/holddownspot01.wav", "vo/npc/male01/holddownspot02.wav", true)
ChatBox.AddSound("i'm hurt", "vo/npc/male01/imhurt01.wav", "vo/npc/male01/imhurt02.wav", true)
ChatBox.AddSound("im hurt", "vo/npc/male01/imhurt01.wav", "vo/npc/male01/imhurt02.wav", true)
ChatBox.AddSound("sometimes i dream about cheese", "vo/npc/male01/question06.wav", true)
ChatBox.AddSound("i can't remember the last time i had a shower", "vo/npc/male01/question19.wav", true)
ChatBox.AddSound("watch what you're doing", "vo/npc/male01/watchwhat.wav", true)
ChatBox.AddSound("you got it", "vo/npc/male01/yougotit02.wav")
ChatBox.AddSound("we thought you were here to help", "vo/npc/male01/heretohelp01.wav", "vo/npc/male01/heretohelp02.wav", true)
ChatBox.AddSound("hey doc", "vo/npc/male01/heydoc01.wav", "vo/npc/male01/heydoc02.wav", true)
ChatBox.AddSound("hit in the gut", "vo/npc/male01/hitingut01.wav", "vo/npc/male01/hitingut02.wav", true)
ChatBox.AddSound("like that?", "vo/npc/male01/likethat.wav", true)
ChatBox.AddSound("my leg", "vo/npc/male01/myleg01.wav", "vo/npc/male01/myleg02.wav", true)
ChatBox.AddSound("my gut", "vo/npc/male01/mygut02.wav", true)
ChatBox.AddSound("my arm", "vo/npc/male01/myarm01.wav", "vo/npc/male01/myarm02.wav", true)
ChatBox.AddSound("no no", "vo/npc/male01/no01.wav")
ChatBox.AddSound("you're not the man i thought you were", "vo/npc/male01/notthemanithought01.wav", true)
ChatBox.AddSound("one for me and one for me", "vo/npc/male01/oneforme.wav", true)
ChatBox.AddSound("let me get out of your way", "vo/npc/male01/outofyourway02.wav", true)
ChatBox.AddSound("i don't think this war is ever going to end", "vo/npc/male01/question01.wav", true)
ChatBox.AddSound("to think all i used to want to do is sell insurance", "vo/npc/male01/question02.wav", true)
ChatBox.AddSound("i don't dream anymore", "vo/npc/male01/question03.wav", true)
ChatBox.AddSound("when this is all over ah who am i kidding", "vo/npc/male01/question04.wav", true)
ChatBox.AddSound("woah deja vu", "vo/npc/male01/question05.wav", true)
ChatBox.AddSound("you smell that? it's freedom", "vo/npc/male01/question07.wav", true)
ChatBox.AddSound("if i ever get my hands on dr. breen", "vo/npc/male01/question08.wav", true)
ChatBox.AddSound("i could eat a horse hooves and all", "vo/npc/male01/question09.wav", true)
ChatBox.AddSound("i can't believe this day has finally come", "vo/npc/male01/question10.wav", true)
ChatBox.AddSound("i'm pretty sure this isn't part of the plan", "vo/npc/male01/question11.wav", true)
ChatBox.AddSound("looks to me like things are getting worse not better", "vo/npc/male01/question12.wav", true)
ChatBox.AddSound("if i could live my life over again", "vo/npc/male01/question13.wav", true)
ChatBox.AddSound("i'm not even gonna tell you what that reminds me of", "vo/npc/male01/question14.wav", true)
ChatBox.AddSound("they're never gonna make a stalker outta me", "vo/npc/male01/question15.wav", true)
ChatBox.AddSound("finally change is in the air", "vo/npc/male01/question16.wav", true)
ChatBox.AddSound("you feel it? i feel it", "vo/npc/male01/question17.wav", true)
ChatBox.AddSound("i don't feel anything anymore", "vo/npc/male01/question18.wav", true)
ChatBox.AddSound("some day this will all be a bad memory", "vo/npc/male01/question20.wav", true)
ChatBox.AddSound("i'm not a betting man but the odds are not good", "vo/npc/male01/question21.wav", true)
ChatBox.AddSound("doesn't anyone care what i think?", "vo/npc/male01/question22.wav", true)
ChatBox.AddSound("i can't get this tune outta my head", "vo/npc/male01/question23.wav", true)
ChatBox.AddSound("i just knew it was gonna be one of those days", "vo/npc/male01/question25.wav", true)
ChatBox.AddSound("i think i ate something bad", "vo/npc/male01/question27.wav", true)
ChatBox.AddSound("when this is all over i'm gonna mate", "vo/npc/male01/question29.wav", true)
ChatBox.AddSound("i'm glad there's no kids around to see this", "vo/npc/male01/question30.wav", true)
ChatBox.AddSound("scanners", "vo/npc/male01/scanners01.wav", true)
ChatBox.AddSound("whatever you say", "vo/npc/male01/squad_affirm03.wav")
ChatBox.AddSound("ok i'm going", "vo/npc/male01/squad_affirm04.wav", true)
ChatBox.AddSound("here it goes", "vo/npc/male01/squad_affirm05.wav", true)
ChatBox.AddSound("here goes nothing", "vo/npc/male01/squad_affirm06.wav", true)
ChatBox.AddSound("here we come", "vo/npc/male01/squad_approach02.wav", true)
ChatBox.AddSound("on our way", "vo/npc/male01/squad_approach03.wav", true)
ChatBox.AddSound("coming", "vo/npc/male01/squad_approach04.wav")
ChatBox.AddSound("this way gang", "vo/npc/male01/squad_away01.wav", true)
ChatBox.AddSound("over here", "vo/npc/male01/squad_away02.wav")
ChatBox.AddSound("let's get moving", "npc/male01/squad_follow03.wav")
ChatBox.AddSound("gordon freeman, you're here", "vo/npc/male01/squad_greet01.wav", true)
ChatBox.AddSound("stop it freeman", "vo/npc/male01/stopitfm.wav", true)
ChatBox.AddSound("strider", "vo/npc/male01/strider.wav", true)
ChatBox.AddSound("this'll do nicely", "vo/npc/male01/thislldonicely01.wav", true)
ChatBox.AddSound("damn vorts", "vo/npc/male01/vanswer02.wav", true)
ChatBox.AddSound("i'm not sure how to take that", "vo/npc/male01/vanswer03.wav", true)
ChatBox.AddSound("should i take that personally?", "vo/npc/male01/vanswer04.wav", true)
ChatBox.AddSound("speak english", "vo/npc/male01/vanswer05.wav", true)
ChatBox.AddSound("you got that from me", "vo/npc/male01/vanswer06.wav", true)
ChatBox.AddSound("that's why we put up with you", "vo/npc/male01/vanswer07.wav", true)
ChatBox.AddSound("couldn't have put it better myself", "vo/npc/male01/vanswer08.wav", true)
ChatBox.AddSound("that almost made sense", "vo/npc/male01/vanswer09.wav", true)
ChatBox.AddSound("something must be wrong with me i almost understood that", "vo/npc/male01/vanswer10.wav", true)
ChatBox.AddSound("i guess i'm getting used to you vorts", "vo/npc/male01/vanswer11.wav", true)
ChatBox.AddSound("none of your vort philosophy", "vo/npc/male01/vanswer12.wav", true)
ChatBox.AddSound("stop you're killing me", "vo/npc/male01/vanswer13.wav", true)
ChatBox.AddSound("what did i do to deserve this?", "vo/npc/male01/vanswer14.wav", true)
ChatBox.AddSound("stop looking at me like that", "vo/npc/male01/vquestion01.wav", true)
ChatBox.AddSound("some things i just never get used to", "vo/npc/male01/vquestion02.wav", true)
ChatBox.AddSound("i don't know how you things survived as long as you have", "vo/npc/male01/vquestion03.wav", true)
ChatBox.AddSound("sometimes i wonder how i ended up with you", "vo/npc/male01/vquestion04.wav", true)
ChatBox.AddSound("you're alright vorty", "vo/npc/male01/vquestion05.wav", true)
ChatBox.AddSound("you vorts aren't half bad", "vo/npc/male01/vquestion06.wav", true)
ChatBox.AddSound("if anyone ever told me i'd be pals with a vortigaunt", "vo/npc/male01/vquestion07.wav", true)
ChatBox.AddSound("you waiting for somebody?", "vo/npc/male01/waitingsomebody.wav", true)
ChatBox.AddSound("woops", "vo/npc/male01/whoops01.wav", true)
ChatBox.AddSound("you'd better reload", "vo/npc/male01/youdbetterreload01.wav", true)
ChatBox.AddSound("bring it on", "vo/npc/Barney/ba_bringiton.wav", true)
ChatBox.AddSound("damnit", "vo/npc/Barney/ba_damnit.wav")
ChatBox.AddSound("i don't like the looks of this", "vo/npc/Barney/ba_danger02.wav", true)
ChatBox.AddSound("down you go", "vo/npc/Barney/ba_downyougo.wav", true)
ChatBox.AddSound("duck", "vo/npc/Barney/ba_duck.wav")
ChatBox.AddSound("come on", "vo/npc/Barney/ba_followme02.wav")
ChatBox.AddSound("get away from there", "vo/npc/Barney/ba_getaway.wav")
ChatBox.AddSound("get outta the way", "vo/npc/Barney/ba_getoutofway.wav")
ChatBox.AddSound("you're going down", "vo/npc/Barney/ba_goingdown.wav", true)
ChatBox.AddSound("grenade", "vo/npc/Barney/ba_grenade01.wav")
ChatBox.AddSound("here it comes!", "vo/npc/Barney/ba_hereitcomes.wav", true)
ChatBox.AddSound("hurry up", "vo/npc/Barney/ba_hurryup.wav")
ChatBox.AddSound("i'm with you buddy", "vo/npc/Barney/ba_imwithyou.wav", true)
ChatBox.AddSound("maniacal!", "vo/npc/Barney/ba_laugh01.wav", true)
ChatBox.AddSound("yeaheheah", "vo/npc/Barney/ba_laugh03.wav", true)
ChatBox.AddSound("let's do it", "vo/npc/Barney/ba_letsdoit.wav", true)
ChatBox.AddSound("look out!", "vo/npc/Barney/ba_lookout.wav", true)
ChatBox.AddSound("i haven't lost my touch", "vo/npc/Barney/ba_losttouch.wav", true)
ChatBox.AddSound("ohoh yeah", "vo/npc/Barney/ba_ohyeah.wav", true)
ChatBox.AddSound("soldiers!", "vo/npc/Barney/ba_soldiers.wav", true)
ChatBox.AddSound("turret!", "vo/npc/Barney/ba_turret.wav", true)
ChatBox.AddSound("uh oh here they come", "vo/npc/Barney/ba_uhohheretheycome.wav", true)
ChatBox.AddSound("i need to get patched up", "vo/npc/Barney/ba_wounded02.wav", true)
ChatBox.AddSound("i'm hurt pretty bad", "vo/npc/Barney/ba_wounded03.wav", true)
ChatBox.AddSound("i know you will", "vo/NovaProspekt/eli_iknow.wav")
ChatBox.AddSound("nevermind me save yourselves", "vo/NovaProspekt/eli_nevermindme01.wav", true)
ChatBox.AddSound("i'll see you there baby", "vo/NovaProspekt/eli_notime01.wav", true)
ChatBox.AddSound("so this is the combine portal it's smaller than i imagined", "vo/NovaProspekt/eli_thisisportal.wav", true)
ChatBox.AddSound("but where will you go?", "vo/NovaProspekt/eli_wherewillyougo01.wav", true)
ChatBox.AddSound("instinct1", "vo/Breencast/br_instinct01.wav", true)
ChatBox.AddSound("instinct2", "vo/Breencast/br_instinct03.wav", true)
ChatBox.AddSound("instinct3", "vo/Breencast/br_instinct08.wav", true)
ChatBox.AddSound("instinct4", "vo/Breencast/br_instinct09.wav", true)
ChatBox.AddSound("instinct5", "vo/Breencast/br_instinct12.wav", true)
ChatBox.AddSound("instinct6", "vo/Breencast/br_instinct14.wav", true)
ChatBox.AddSound("instinct7", "vo/Breencast/br_instinct15.wav", true)
ChatBox.AddSound("instinct8", "vo/Breencast/br_instinct16.wav", true)
ChatBox.AddSound("instinct9", "vo/Breencast/br_instinct17.wav", true)
ChatBox.AddSound("instinct10", "vo/Breencast/br_instinct18.wav", true)
ChatBox.AddSound("instinct11", "vo/Breencast/br_instinct19.wav", true)
ChatBox.AddSound("instinct12", "vo/Breencast/br_instinct20.wav", true)
ChatBox.AddSound("instinct13", "vo/Breencast/br_instinct21.wav", true)
ChatBox.AddSound("instinct14", "vo/Breencast/br_instinct22.wav", true)
ChatBox.AddSound("instinct15", "vo/Breencast/br_instinct23.wav", true)
ChatBox.AddSound("instinct16", "vo/Breencast/br_instinct25.wav", true)
ChatBox.AddSound("you have plunged humanity in to free fall", "vo/Breencast/br_tofreeman06.wav", true)
ChatBox.AddSound("even if you offered your surrunder now", "vo/Breencast/br_tofreeman07.wav", true)
ChatBox.AddSound("help ensure that humanity's trust in you is not misguided", "vo/Breencast/br_tofreeman10.wav", true)
ChatBox.AddSound("they're shelling us", "vo/canals/male01/stn6_shellingus.wav", true)
ChatBox.AddSound("incoming!", "vo/canals/male01/stn6_incoming.wav", true)
ChatBox.AddSound("you can park the boat it'll be safe here", "vo/canals/male01/gunboat_parkboat.wav", true)
ChatBox.AddSound("let's get a move on we gotta move out before they target us", "vo/canals/male01/gunboat_moveon.wav", true)
ChatBox.AddSound("you made it just in time we gotta clear outta here before we're discovered", "vo/canals/male01/gunboat_justintime.wav", true)
ChatBox.AddSound("we'd better hurry we gotta tear down this camp and get outta here", "vo/canals/male01/gunboat_hurry.wav", true)
ChatBox.AddSound("be careful now", "vo/canals/boxcar_becareful.wav", true)
ChatBox.AddSound("we really can't afford to get noticed", "vo/canals/boxcar_becareful_b.wav", true)
ChatBox.AddSound("better get going", "vo/canals/boxcar_go_nag02.wav", true)
ChatBox.AddSound("he'll help you if you let him", "vo/canals/boxcar_lethimhelp.wav", true)
ChatBox.AddSound("we're just a lookout for the underground railroad", "vo/canals/boxcar_lookout.wav", true)
ChatBox.AddSound("main station's right around the corner", "vo/canals/boxcar_lookout_b.wav", true)
ChatBox.AddSound("they'll get you started on the right foot", "vo/canals/boxcar_lookout_d.wav", true)
ChatBox.AddSound("guess those sirens are for you", "vo/canals/boxcar_sirens.wav", true)
ChatBox.AddSound("come on in i'll show you what you're up against", "vo/canals/gunboat_comein.wav", true)
ChatBox.AddSound("i think he's just finishing up now", "vo/canals/gunboat_finishingup.wav", true)
ChatBox.AddSound("come on get in here", "vo/canals/gunboat_getin.wav", true)
ChatBox.AddSound("here take a look at this", "vo/canals/gunboat_herelook.wav", true)
ChatBox.AddSound("be glad you're not the guy they're looking for", "vo/canals/matt_beglad.wav", true)
ChatBox.AddSound("poor bastard doesn't stand a chance", "vo/canals/matt_beglad_b.wav", true)
ChatBox.AddSound("sounds like they're calling in every cp unit in city 17", "vo/canals/matt_beglad_c.wav", true)
ChatBox.AddSound("that was a close call thanks for your help", "vo/canals/matt_closecall.wav", true)
ChatBox.AddSound("now they're flooding the areas up ahead with manhacks", "vo/canals/matt_flood.wav", true)
ChatBox.AddSound("you'd better get going before they sweep through here", "vo/canals/matt_flood_b.wav", true)
ChatBox.AddSound("you'd better get going now", "vo/canals/matt_go_nag01.wav", true)
ChatBox.AddSound("thanks but i'll be ok", "vo/canals/matt_go_nag02.wav", true)
ChatBox.AddSound("i've got to stay and help any stragglers", "vo/canals/matt_go_nag03.wav", true)
ChatBox.AddSound("you go on", "vo/canals/matt_go_nag05.wav", true)
ChatBox.AddSound("good luck out there", "vo/canals/matt_goodluck.wav", true)
ChatBox.AddSound("civil protection is on to us", "vo/canals/matt_tearinguprr.wav", true)
ChatBox.AddSound("we're tearing up the railroad covering our tracks", "vo/canals/matt_tearinguprr_a.wav", true)
ChatBox.AddSound("looks like you're gonna be the last one through", "vo/canals/matt_tearinguprr_b.wav", true)
ChatBox.AddSound("thanks for the help but you better get outta here", "vo/canals/matt_thanksbut.wav", true)
ChatBox.AddSound("oh shit too late", "vo/canals/matt_toolate.wav", true)
ChatBox.AddSound("you got here at a bad time", "vo/canals/shanty_badtime.wav", true)
ChatBox.AddSound("we got some ammo in those crates over there", "vo/canals/shanty_gotsomeammo.wav", true)
ChatBox.AddSound("we got word you were coming", "vo/canals/shanty_gotword.wav", true)
ChatBox.AddSound("help yourself to supplies and keep moving", "vo/canals/shanty_helpyourself.wav", true)
ChatBox.AddSound("did you realize your contract was open to the highest bidder?", "vo/Citadel/br_bidder_b.wav", true)
ChatBox.AddSound("that's all up to you my old friend", "vo/Citadel/br_gift_a.wav", true)
ChatBox.AddSound("will you give your child a chance her mother never had?", "vo/Citadel/br_gift_c.wav", true)
ChatBox.AddSound("what's this oh put it over there", "vo/Citadel/br_gravgun.wav", true)
ChatBox.AddSound("guards get in here", "vo/Citadel/br_guards.wav", true)
ChatBox.AddSound("you have my gratitude doctor", "vo/Citadel/br_guest_b.wav", true)
ChatBox.AddSound("and then you deliver yourself?", "vo/Citadel/br_guest_d.wav", true)
ChatBox.AddSound("i don't know what you can possibly hope to achieve", "vo/Citadel/br_mock05.wav", true)
ChatBox.AddSound("i warned you this was futile", "vo/Citadel/br_mock06.wav", true)
ChatBox.AddSound("i hope you said your farewells", "vo/Citadel/br_mock09.wav", true)
ChatBox.AddSound("if only you had harnessed your boundless energy for a useful purpose", "vo/Citadel/br_mock13.wav", true)
ChatBox.AddSound("i agree it's a total waste", "vo/Citadel/br_newleader_a.wav", true)
ChatBox.AddSound("this one has proven to be a fine pawn", "vo/Citadel/br_newleader_c.wav", true)
ChatBox.AddSound("i understand if you don't wish to discuss this in front of your friends", "vo/Citadel/br_nothingtosay_a.wav", true)
ChatBox.AddSound("i'll send them on their way and then we can talk openly", "vo/Citadel/br_nothingtosay_b.wav", true)
ChatBox.AddSound("impossible to describe with our limited vocabulary", "vo/Citadel/br_oheli09.wav", true)
ChatBox.AddSound("oh shit", "vo/Citadel/br_ohshit.wav", true)
ChatBox.AddSound("if you won't do the right thing for the good of all people", "vo/Citadel/br_playgame_b.wav", true)
ChatBox.AddSound("maybe you'll do it for one of them", "vo/Citadel/br_playgame_c.wav", true)
ChatBox.AddSound("thanks to you we have everything we need in that regard", "vo/Citadel/br_rabble_a.wav", true)
ChatBox.AddSound("you're more than qualified to finish his research yourself", "vo/Citadel/br_rabble_b.wav", true)
ChatBox.AddSound("if that's what it takes", "vo/Citadel/br_whatittakes.wav", true)
ChatBox.AddSound("you need me", "vo/Citadel/br_youneedme.wav", true)
ChatBox.AddSound("don't struggle honey", "vo/Citadel/eli_dontstruggle.wav", true)
ChatBox.AddSound("don't worry about me", "vo/Citadel/eli_dontworryboutme.wav", true)
ChatBox.AddSound("that's my girl", "vo/Citadel/eli_mygirl.wav", true)
ChatBox.AddSound("save them for what", "vo/Citadel/eli_save.wav", true)
ChatBox.AddSound("is it really that time again?", "vo/Citadel/gman_exit02.wav", true)
ChatBox.AddSound("i'm really not at liberty to say", "vo/Citadel/gman_exit08.wav", true)
ChatBox.AddSound("in the meantime", "vo/Citadel/gman_exit09.wav", true)
ChatBox.AddSound("this is where i get off", "vo/Citadel/gman_exit10.wav", true)
ChatBox.AddSound("they're looking for your car", "vo/coast/barn/male01/chatter.wav", true)
ChatBox.AddSound("here come the dropships", "vo/coast/barn/male01/crapships.wav", true)
ChatBox.AddSound("right along there and watch your step", "vo/coast/barn/male01/exit_watchstep.wav", true)
ChatBox.AddSound("get your car in the barn", "vo/coast/barn/male01/getcarinbarn.wav", true)
ChatBox.AddSound("get your car in the garage", "vo/coast/barn/male01/getcaringarage.wav", true)
ChatBox.AddSound("get off the road", "vo/coast/barn/male01/getoffroad01.wav", true)
ChatBox.AddSound("incoming dropship", "vo/coast/barn/male01/incomingdropship.wav", true)
ChatBox.AddSound("it's a gunship", "vo/coast/barn/male01/lite_gunship01.wav", true)
ChatBox.AddSound("gunship", "vo/coast/barn/male01/lite_gunship02.wav", true)
ChatBox.AddSound("park it there", "vo/coast/barn/male01/parkit.wav", true)
ChatBox.AddSound("you made it", "vo/coast/barn/male01/youmadeit.wav", true)
ChatBox.AddSound("you idiot walking on the sand brings antlions after you", "vo/coast/bugbait/sandy_youidiot.wav", true)
ChatBox.AddSound("you there", "vo/coast/bugbait/sandy_youthere.wav", true)
ChatBox.AddSound("stop where you are stay on the rocks", "vo/coast/bugbait/sandy_stop.wav", true)
ChatBox.AddSound("no! help!", "vo/coast/bugbait/sandy_help.wav", true)
ChatBox.AddSound("yeah good idea hold on a sec", "vo/coast/cardock/le_goodidea.wav", true)
ChatBox.AddSound("patch him up and get him to the back as soon as he's stable", "vo/coast/cardock/le_patchhim.wav", true)
ChatBox.AddSound("i'll radio ahead to let the next base know you're coming", "vo/coast/cardock/le_radio.wav", true)
ChatBox.AddSound("who's hurt?", "vo/coast/cardock/le_whohurt.wav", true)
ChatBox.AddSound("well that's that", "vo/coast/odessa/nlo_cub_thatsthat.wav", true)
ChatBox.AddSound("i couldn't have asked for a finer volunteer", "vo/coast/odessa/nlo_cub_volunteer.wav", true)
ChatBox.AddSound("you'll make it through if anyone can", "vo/coast/odessa/nlo_cub_youllmakeit.wav", true)
ChatBox.AddSound("good to know you", "vo/eli_lab/airlock_cit01.wav", true)
ChatBox.AddSound("you'd better get going", "vo/eli_lab/airlock_cit02.wav", true)
ChatBox.AddSound("awesome!", "vo/eli_lab/al_awesome.wav", true)
ChatBox.AddSound("alright good you keep right on it", "vo/eli_lab/eli_goodvort.wav", true)
ChatBox.AddSound("ughghgh", "vo/eli_lab/eli_handle_b.wav", true)
ChatBox.AddSound("ughhh", "vo/k_lab/ba_thingaway02.wav", true)
ChatBox.AddSound("feel free to look around", "vo/eli_lab/eli_lookaround.wav", true)
ChatBox.AddSound("dr. breen", "vo/eli_lab/eli_vilebiz01.wav", true)
ChatBox.AddSound("i can't look", "vo/k_lab/ba_cantlook.wav", true)
ChatBox.AddSound("careful", "vo/k_lab/ba_careful01.wav")
ChatBox.AddSound("be careful!", "vo/k_lab/ba_careful01.wav", true)
ChatBox.AddSound("forget about that thing", "vo/k_lab/ba_forgetthatthing.wav", true)
ChatBox.AddSound("get it off me", "vo/k_lab/ba_getitoff02.wav", true)
ChatBox.AddSound("get down outta sight", "vo/k_lab/ba_getoutofsight01.wav", true)
ChatBox.AddSound("i'll come find you", "vo/k_lab/ba_getoutofsight02.wav", true)
ChatBox.AddSound("guh", "vo/k_lab/ba_guh.wav", true)
ChatBox.AddSound("hey hey he's back", "vo/k_lab/ba_hesback01.wav", true)
ChatBox.AddSound("i'm getting him outta there", "vo/k_lab/ba_hesback02.wav", true)
ChatBox.AddSound("well is he here?", "vo/k_lab/ba_ishehere.wav", true)
ChatBox.AddSound("you mean it's working?", "vo/k_lab/ba_itsworking01.wav", true)
ChatBox.AddSound("for real this time?", "vo/k_lab/ba_itsworking02.wav", true)
ChatBox.AddSound("i still have nightmares about that cat", "vo/k_lab/ba_itsworking04.wav", true)
ChatBox.AddSound("i've gotta get back on my shift", "vo/k_lab/ba_myshift01.wav", true)
ChatBox.AddSound("but ok", "vo/k_lab/ba_myshift02.wav")
ChatBox.AddSound("yeah longer if we're lucky", "vo/k_lab/ba_longer.wav", true)
ChatBox.AddSound("and not a moment too soon", "vo/k_lab/ba_nottoosoon01.wav", true)
ChatBox.AddSound("that's what you said last time", "vo/k_lab/ba_saidlasttime.wav", true)
ChatBox.AddSound("i can tell your mit education really pays for itself", "vo/k_lab/ba_sarcastic03.wav", true)
ChatBox.AddSound("i thought you got rid of that pest", "vo/k_lab/ba_thatpest.wav", true)
ChatBox.AddSound("there he is", "vo/k_lab/ba_thereheis.wav", true)
ChatBox.AddSound("there you are", "vo/k_lab/ba_thereyouare.wav", true)
ChatBox.AddSound("here we go", "vo/k_lab/ba_thingaway01.wav", true)
ChatBox.AddSound("get that thing away from me", "vo/k_lab/ba_thingaway03.wav", true)
ChatBox.AddSound("what's the meaning of this?", "vo/k_lab/br_tele_02.wav", true)
ChatBox.AddSound("who are you?", "vo/k_lab/br_tele_03.wav")
ChatBox.AddSound("how did you get in here?", "vo/k_lab/br_tele_05.wav", true)
ChatBox.AddSound("see for yourself", "vo/k_lab/eli_seeforyourself.wav", true)
ChatBox.AddSound("shut it down shut it down", "vo/k_lab/eli_shutdown.wav", true)
ChatBox.AddSound("ahhhh", "vo/k_lab/kl_ahhhh.wav", true)
ChatBox.AddSound("there's a charger on the wall", "vo/k_lab/kl_charger01.wav", true)
ChatBox.AddSound("dear me", "vo/k_lab/kl_dearme.wav", true)
ChatBox.AddSound("well did it work?", "vo/k_lab/kl_diditwork.wav", true)
ChatBox.AddSound("excellent!", "vo/k_lab/kl_excellent.wav", true)
ChatBox.AddSound("right you are", "vo/k_lab/kl_fewmoments01.wav", true)
ChatBox.AddSound("speak to you again in a few moments", "vo/k_lab/kl_fewmoments02.wav", true)
ChatBox.AddSound("oh fiddlesticks what now", "vo/k_lab/kl_fiddlesticks.wav", true)
ChatBox.AddSound("final sequence", "vo/k_lab/kl_finalsequence02.wav", true)
ChatBox.AddSound("you must get out of here", "vo/k_lab/kl_getoutrun02.wav", true)
ChatBox.AddSound("run!", "vo/k_lab/kl_getoutrun03.wav", true)
ChatBox.AddSound("here my pet", "vo/k_lab/kl_heremypet01.wav", true)
ChatBox.AddSound("no not up there", "vo/k_lab/kl_heremypet02.wav", true)
ChatBox.AddSound("interference!", "vo/k_lab/kl_interference.wav", true)
ChatBox.AddSound("lamarr", "vo/k_lab/kl_hedyno01.wav", true)
ChatBox.AddSound("heady", "vo/k_lab/kl_hedyno02.wav", true)
ChatBox.AddSound("is lamarr with him?", "vo/k_lab/kl_islamarr.wav", true)
ChatBox.AddSound("lamarr there you are", "vo/k_lab/kl_lamarr.wav", true)
ChatBox.AddSound("careful lamarr those are quite fragile", "vo/k_lab/kl_nocareful.wav", true)
ChatBox.AddSound("conditions could hardly be more ideal", "vo/k_lab/kl_moduli02.wav", true)
ChatBox.AddSound("my goodness", "vo/k_lab/kl_mygoodness01.wav", true)
ChatBox.AddSound("it really is you isn't it?", "vo/k_lab/kl_mygoodness03.wav", true)
ChatBox.AddSound("your talents surpass your loveliness", "vo/k_lab/kl_nonsense.wav", true)
ChatBox.AddSound("oh dear", "vo/k_lab/kl_ohdear.wav", true)
ChatBox.AddSound("indeed it is", "vo/k_lab/kl_packing01.wav", true)
ChatBox.AddSound("slip in to your suit now", "vo/k_lab/kl_slipin02.wav", true)
ChatBox.AddSound("i'm eager to see if your old suit still fits", "vo/k_lab/kl_suitfits02.wav", true)
ChatBox.AddSound("then where is he?", "vo/k_lab/kl_thenwhere.wav", true)
ChatBox.AddSound("what is it?", "vo/k_lab/kl_whatisit.wav")
ChatBox.AddSound("i wish i knew!", "vo/k_lab/kl_wishiknew.wav", true)
ChatBox.AddSound("go on get going", "vo/k_lab2/ba_getgoing.wav", true)
ChatBox.AddSound("well man that's good news", "vo/k_lab2/ba_goodnews.wav", true)
ChatBox.AddSound("i almost gave you guys up for lost", "vo/k_lab2/ba_goodnews_b.wav", true)
ChatBox.AddSound("i'll take all the help i can get", "vo/k_lab2/ba_goodnews_c.wav", true)
ChatBox.AddSound("aw crap incoming!", "vo/k_lab2/ba_incoming.wav", true)
ChatBox.AddSound("so there you see?", "vo/k_lab2/kl_notallhopeless.wav", true)
ChatBox.AddSound("it's not all hopeless", "vo/k_lab2/kl_notallhopeless_b.wav", true)
ChatBox.AddSound("there's only one heady", "vo/k_lab2/kl_onehedy.wav", true)
ChatBox.AddSound("fascinating!", "vo/k_lab2/kl_slowteleport01.wav", true)
ChatBox.AddSound("aim for the head", "vo/ravenholm/aimforthehead.wav", true)
ChatBox.AddSound("guard yourself well", "vo/ravenholm/bucket_guardwell.wav", true)
ChatBox.AddSound("there you are at last", "vo/ravenholm/bucket_thereyouare.wav", true)
ChatBox.AddSound("better than better", "vo/ravenholm/cartrap_better.wav", true)
ChatBox.AddSound("yes come to me come", "vo/ravenholm/engage01.wav", true)
ChatBox.AddSound("come!", "vo/ravenholm/engage02.wav", "vo/ravenholm/engage03.wav", true)
ChatBox.AddSound("i will end your torment", "vo/ravenholm/engage04.wav", true)
ChatBox.AddSound("let me end your torment", "vo/ravenholm/engage05.wav", true)
ChatBox.AddSound("yes my children it is i", "vo/ravenholm/engage06.wav", true)
ChatBox.AddSound("come to the light i carry come", "vo/ravenholm/engage07.wav", true)
ChatBox.AddSound("it is not me you want but the light that shines through me", "vo/ravenholm/engage08.wav", true)
ChatBox.AddSound("come to the light", "vo/ravenholm/engage09.wav", true)
ChatBox.AddSound("go quickly", "vo/ravenholm/exit_goquickly.wav", true)
ChatBox.AddSound("hurry while i hold the gate", "vo/ravenholm/exit_hurry.wav", true)
ChatBox.AddSound("flee brother", "vo/ravenholm/exit_nag01.wav", true)
ChatBox.AddSound("onward to the mines", "vo/ravenholm/exit_nag02.wav", true)
ChatBox.AddSound("look out brother behind you", "vo/ravenholm/firetrap_lookout.wav", true)
ChatBox.AddSound("well done brother", "vo/ravenholm/firetrap_welldone.wav", true)
ChatBox.AddSound("stay close to me brother", "vo/ravenholm/grave_stayclose.wav", true)
ChatBox.AddSound("out of my way", "vo/ravenholm/monk_blocked01.wav", true)
ChatBox.AddSound("look out", "vo/ravenholm/monk_blocked02.wav")
ChatBox.AddSound("stand aside brother", "vo/ravenholm/monk_blocked03.wav", true)
ChatBox.AddSound("cover me brother", "vo/ravenholm/monk_coverme01.wav", true)
ChatBox.AddSound("your assistance brother", "vo/ravenholm/monk_coverme02.wav", true)
ChatBox.AddSound("over here brother", "vo/ravenholm/monk_coverme03.wav", true)
ChatBox.AddSound("to me brother", "vo/ravenholm/monk_coverme04.wav", true)
ChatBox.AddSound("i require your assistance brother", "vo/ravenholm/monk_coverme05.wav", true)
ChatBox.AddSound("where art thou brother", "vo/ravenholm/monk_coverme07.wav", true)
ChatBox.AddSound("beware!", "vo/ravenholm/monk_danger02.wav", true)
ChatBox.AddSound("careful brother", "vo/ravenholm/monk_danger03.wav", true)
ChatBox.AddSound("i am outnumbered", "vo/ravenholm/monk_helpme01.wav", true)
ChatBox.AddSound("help me brother", "vo/ravenholm/monk_helpme02.wav", true)
ChatBox.AddSound("i cannot fight them all alone", "vo/ravenholm/monk_helpme03.wav", true)
ChatBox.AddSound("lend a hand brother", "vo/ravenholm/monk_helpme04.wav", true)
ChatBox.AddSound("i need help brother", "vo/ravenholm/monk_helpme05.wav", true)
ChatBox.AddSound("rest my child", "vo/ravenholm/monk_kill03.wav", true)
ChatBox.AddSound("i think no worse of thee", "vo/ravenholm/monk_kill04.wav", true)
ChatBox.AddSound("may the light of lights be with you", "vo/ravenholm/monk_kill05.wav", true)
ChatBox.AddSound("you meant no harm", "vo/ravenholm/monk_kill06.wav", true)
ChatBox.AddSound("be free my child", "vo/ravenholm/monk_kill09.wav", true)
ChatBox.AddSound("the grave holds nothing worse for you", "vo/ravenholm/monk_kill10.wav", true)
ChatBox.AddSound("i remember your true face", "vo/ravenholm/monk_kill11.wav", true)
ChatBox.AddSound("so again i am alone", "vo/ravenholm/monk_mourn03.wav", true)
ChatBox.AddSound("my advice to you is aim for the head", "vo/ravenholm/shotgun_advice.wav", true)
ChatBox.AddSound("here i have a more suitable gun for you", "vo/ravenholm/shotgun_bettergun.wav", true)
ChatBox.AddSound("catch!", "vo/ravenholm/shotgun_catch.wav", true)
ChatBox.AddSound("come closer", "vo/ravenholm/shotgun_closer.wav", true)
ChatBox.AddSound("hush", "vo/ravenholm/shotgun_hush.wav")
ChatBox.AddSound("good now keep it close", "vo/ravenholm/shotgun_keepitclose.wav", true)
ChatBox.AddSound("they come", "vo/ravenholm/shotgun_theycome.wav", true)
ChatBox.AddSound("if you can hold them off i'm almost done here", "vo/Streetwar/tunnel/male01/c17_06_det02.wav", true)
ChatBox.AddSound("stand back it's gonna blow", "vo/Streetwar/tunnel/male01/c17_06_det04.wav", true)
ChatBox.AddSound("hey it's me open the door", "vo/Streetwar/tunnel/male01/c17_06_password01.wav", true)
ChatBox.AddSound("what's the password?", "vo/Streetwar/tunnel/male01/c17_06_password02.wav", true)
ChatBox.AddSound("password!", "vo/Streetwar/tunnel/male01/c17_06_password03.wav", true)
ChatBox.AddSound("come on in", "vo/Streetwar/tunnel/male01/c17_06_password04.wav", true)
ChatBox.AddSound("ok come across", "vo/Streetwar/tunnel/male01/c17_06_plank01.wav", true)
ChatBox.AddSound("that damn thing haunts me", "vo/Streetwar/sniper/ba_hauntsme.wav", true)
ChatBox.AddSound("did you hear a cat just now?", "vo/Streetwar/sniper/ba_hearcat.wav", true)
ChatBox.AddSound("hey come on", "vo/Streetwar/sniper/ba_heycomeon.wav", true)
ChatBox.AddSound("let's get going", "vo/Streetwar/sniper/ba_letsgetgoing.wav", true)
ChatBox.AddSound("heeelp", "vo/Streetwar/sniper/male01/c17_09_help01.wav", true)
ChatBox.AddSound("help me!", "vo/Streetwar/sniper/male01/c17_09_help02.wav", true)
ChatBox.AddSound("is somebody up there?", "vo/Streetwar/sniper/male01/c17_09_help03.wav", true)
ChatBox.AddSound("damnit all", "vo/Streetwar/rubble/ba_damnitall.wav", true)
ChatBox.AddSound("hey help me out here", "vo/Streetwar/rubble/ba_helpmeout.wav", true)
ChatBox.AddSound("well i'll be damned", "vo/Streetwar/rubble/ba_illbedamned.wav", true)
ChatBox.AddSound("and if you see dr. breen tell him i said fuck you", "vo/Streetwar/rubble/ba_tellbreen.wav", true)
ChatBox.AddSound("done!", "vo/Streetwar/nexus/ba_done.wav", true)
ChatBox.AddSound("great i'll open this up", "vo/Streetwar/nexus/ba_illopenthis.wav", true)
ChatBox.AddSound("so much for stealth we've been spotted", "vo/Streetwar/nexus/ba_spotted.wav", true)
ChatBox.AddSound("we're surrounded", "vo/Streetwar/nexus/ba_surrounded.wav", true)
ChatBox.AddSound("then let's go", "vo/Streetwar/nexus/ba_thenletsgo.wav", true)
ChatBox.AddSound("uh oh dropships", "vo/Streetwar/nexus/ba_uhohdropships.wav", true)
ChatBox.AddSound("hey let us outta here", "vo/Streetwar/nexus/male01/c17_10_letusout.wav", true)
ChatBox.AddSound("let us thru!", "vo/Streetwar/barricade/male01/c17_05_letusthru.wav", true)
ChatBox.AddSound("let us through!", "vo/Streetwar/barricade/male01/c17_05_letusthru.wav", true)
ChatBox.AddSound("open the gate!", "vo/Streetwar/barricade/male01/c17_05_opengate.wav", true)
ChatBox.AddSound("how dare you even mention her", "vo/Citadel/al_dienow_b.wav", true)
ChatBox.AddSound("alyx my dear you have your mother's eyes but your father's stubborn nature", "vo/Citadel/br_stubborn.wav", true)
ChatBox.AddSound("it isn't necessary", "vo/Citadel/mo_necessary.wav", true)
